### PR TITLE
Reuse servercore layers for nanoserver builds

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@yosefkit

**Comment by ldez** [comment]
How this can work before the availability of `traefik:v3.0.0-windowsservercore-ltsc2022`?

**Comment by LaurentGoderre** [comment]
@ldez our build system establishes the dependencies and builds them in order.

**Comment by ldez** [comment]
ok, I will merge your PR.

I will need to update our templates.

**Pull request merged**
